# Generated by Django 5.1.7 on 2025-03-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('media', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Можете добавить изображение')),
                ('created_at', models.DateTimeField(blank=True, help_text='формат "dd.mm.yy"', null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, help_text='формат "dd.mm.yy"', null=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'наименование записи',
                'verbose_name_plural': 'наименования записей',
            },
        ),
    ]
